apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: course-app
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
